[package]
name = "smoothshot"
version = "0.1.0"
description = "Smooth cinematic screen recording for Windows and macOS"
authors = ["SmoothShot Team"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "smoothshot_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
image = { version = "0.24", default-features = false, features = ["png"] }
hound = "3"

raw-window-handle = "0.6"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Media_Audio",
    "Win32_System_Com",
    "Win32_Graphics_Dxgi",
] }
serde_json = "1"
screenshots = "0.8"
device_query = "2"
wgpu = "25"
pollster = "0.4"
cpal = "0.15"
dirs-next = "2"
